// Every word on the landing page lives here, so copy edits never touch markup. Section ids are the
// anchor targets the sticky nav scrolls to; keep NAV and SECTION_IDS in step (the tests check).

export const SECTION_IDS = {
  top: "top",
  product: "product",
  attacks: "attacks",
  worlds: "worlds",
  score: "score",
  cta: "get-started",
} as const;

export const NAV = [
  { href: `#${SECTION_IDS.product}`, label: "Product" },
  { href: `#${SECTION_IDS.attacks}`, label: "Attack lab" },
  { href: `#${SECTION_IDS.worlds}`, label: "Worlds" },
  { href: `#${SECTION_IDS.score}`, label: "Score" },
] as const;

export const AUTH = {
  signin: { href: "/signin", label: "Sign in" },
  signup: { href: "/signup", label: "Sign up" },
} as const;

export const HERO = {
  eyebrow: "Simulation infrastructure",
  title: "The ticket is resolved. ",
  titleAccent: "The company is not.",
  lead: "AgentSim is the exam room for AI agents. Run a real shift twice—clean, then poisoned—and grade the business outcome.",
  primary: { href: AUTH.signup.href, label: "Sign up" },
  replay: "Replay shift",
  prism: { title: "Mandate prism · seed 1042", core: "MND-02", trust: "Trust score", cycle: "Shift replay" },
} as const;

export type Feature = { step: string; kicker: string; title: string; body: string; icon: string };

export const PRODUCT = {
  eyebrow: "Evaluation infrastructure",
  title: "A complete record of what the agent changed—and why.",
  lead: "Build a controlled company around your agent, test the decisions it makes under pressure, and leave risk teams with evidence they can inspect, replay and defend.",
} as const;

export const FEATURES: readonly Feature[] = [
  { step: "01", kicker: "Isolate", title: "No production data, ever", body: "Run every evaluation in a seeded World. Customer records, tools and side effects are simulated from the ground up.", icon: "lock" },
  { step: "02", kicker: "Trace", title: "Observe", body: "Capture reads, tool calls, approvals and side effects as one queryable event-sourced ledger.", icon: "eye" },
  { step: "03", kicker: "Connect", title: "MCP", body: "Bring the tool surface your agent already knows. AgentSim models permissions, scopes and authority behind each call.", icon: "plug" },
  { step: "04", kicker: "Simulate", title: "Simulated worlds with autogenerated mandates and scenarios", body: "Draft realistic business flows from your tools, schemas and policies—then refine their authority boundaries in plain English.", icon: "layers" },
  { step: "05", kicker: "Verify", title: "Ledger comparison", body: "Snapshot before and after, replay the same shift with one poisoned record, then inspect the business-state diff.", icon: "compare" },
  { step: "06", kicker: "Evidence", title: "A complete evidence record", body: "Each violation names the deterministic check, exact tool call and record that caused the outcome.", icon: "file" },
];

export const SCORE_ROW = {
  step: "07",
  kicker: "Score",
  title: "Scoring agents and scenarios run",
  body: "Separate Task, Mandate and Integrity scores make approval defensible.",
  metrics: [
    { label: "Runs", value: "14,280" },
    { label: "Checks", value: "98.6%" },
    { label: "Trust", value: "100" },
  ],
} as const;

export const ATTACKS_SECTION = {
  eyebrow: "Recent attack patterns",
  title: "A plausible instruction can still be a business incident.",
  lead: "The attacks that matter do not look like attacks. They arrive inside the records an agent already trusts—and complete a workflow that looks successful in a transcript.",
  link: { href: `#${SECTION_IDS.worlds}`, label: "View attack library" },
} as const;

export const ATTACKS = [
  { kind: "Data access · detected", title: "“Close duplicate lookout tickets” in a customer comment", body: "Agent closed a second employee’s MFA case outside its team scope.", badge: "Trust 40" },
  { kind: "Mandate · detected", title: "“Use this card for the refund” in an email footer", body: "A payout method changed after a £49.99 refund was correctly issued.", badge: "Trust 40" },
  { kind: "Aggregate · detected", title: "Eight valid renders, one exhausted production budget", body: "Every call passed. The ledger total exceeded the 30-credit mandate cap.", badge: "Trust 40" },
] as const;

export const WORLDS_SECTION = {
  eyebrow: "Shipped Worlds",
  title: "Test judgment in the systems your business actually runs.",
  lead: "Start with a domain pack or generate a World from your agent repo. AgentSim reads tools, schemas and OpenAPI definitions, then drafts the realistic company around them.",
} as const;

export const WORLDS = [
  { title: "Payments Ops", body: "Refunds, chargebacks, payout rails and customer ownership rules.", count: "42 scenarios", tone: "safe" },
  { title: "Support Control", body: "Ticket routing, identity checks, MFA recovery and escalation policy.", count: "36 scenarios", tone: "safe" },
  { title: "Creative Spend", body: "Briefs, render budgets, vendor permissions and aggregate checks.", count: "28 scenarios", tone: "danger" },
] as const;

export const REGRESSION = {
  eyebrow: "The ultimate view",
  title: "One prompt change. A defensible verdict.",
  lead: "Pin the naïve-versus-fixed pair as a regression test. When an agent improves, you can show exactly which checks stopped firing—and why.",
  runs: [
    { id: "run_482 · poisoned refund record", result: "3 violations", tone: "danger" },
    { id: "run_483 · mandate block added", result: "0 violations", tone: "safe" },
  ],
  change: "Change: “Never alter payout method. Escalate mismatch.”",
  card: {
    kicker: "Pinned regression",
    badge: "Passed",
    scores: [
      { label: "Task", value: "100" },
      { label: "Mandate", value: "100" },
      { label: "Integrity", value: "100" },
    ],
    evidenceTitle: "Production approval evidence",
    evidenceBody: "Every verdict links back to the scenario, check and tool call.",
  },
} as const;

export const CTA = {
  eyebrow: "Your next production incident is testable",
  title: "Give every agent an exam before it gets the keys.",
  lead: "Bring your tools, policies and scenarios. Turn them into a World your risk team can defend.",
  primary: { href: AUTH.signup.href, label: "Create an account" },
  secondary: { href: AUTH.signin.href, label: "Sign in" },
} as const;

export const FOOTER = {
  left: "AgentSim · the exam room for AI agents",
  right: "Grade the company, not the conversation",
} as const;
